### ISSUE TITLE
How to add many to many relationships?

### ISSUE THREAD

**Issue by dancomanlive** [sebas5384/graphql-explorer#4]
Thank you in advance.

**Comment by sebas5384** [comment]
Hi @dancomanlive , could you give me a use of case? because in the world of Graph databases the concept of many-to-many is not so much used since is a more persistence strategy than a way to get your data.

There's a good answer from Lee Byron to a similar question:
https://stackoverflow.com/questions/49903229/many-to-many-relationship-in-graphql
